AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'support/**/*'
    - 'tmp/**/*'
    - 'test/**/*'

Metrics:
  Enabled: false
Style:
  Enabled: false
Layout:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Nameing/VariableName:
  Enabled: false