meta_product_name: 'Loop Beauty'
meta_title: 'Loop Beauty - Perfect your look in one place.'
meta_description: 'Expert advice. Fun secrets. Master classes. Exciting stories. Perfect your look in one place.'
meta_image: 'social-card.png' # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
