meta_product_name: 'The NET'
meta_title: 'The NET: Beauty for women of colour. Perfect your look in one place.'
meta_description: 'Your destination for the best in beauty for Women of Colour - Shop Now. We partner with your favourite experts to curate the best in beauty products. Perfect your look in one place. '
meta_image: 'social-card.png' # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
