meta_product_name: "LoopBeauty"
meta_title: "LoopBeauty - Perfect your look in one place."
meta_description: "Expert advice. Fun secrets. Master classes. Exciting stories. Perfect your look in one place."
meta_image: "loop-beauty-logo.svg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
